# Use the official Python Alpine image
FROM python:3.12-alpine

# Copy the hello.py file into the container
COPY hello.py /app/hello.py

# Set the working directory
WORKDIR /app

# Run the hello.py script when the container starts
CMD ["python", "hello.py"]

